### ISSUE TITLE
Feature request: give option to show/hide navigation buttons 

### ISSUE THREAD

**Issue by SatyamKr07** [sahilsaha7773/react-carousel-minimal#2]
In mobile view especially, we don't need the navigation button as swipe feature is there. In desktop we can enable it for swipe. So please give option to do that.

**Comment by sahilsaha7773** [comment]
Thanks for opening this issue! I will push an update adding this asap.

**Comment by shishirtiwari23** [comment]
@sahilsaha7773 I have already fixed it and will make a PR if Assigned !!

**Comment by sahilsaha7773** [comment]
> @sahilsaha7773 I have already fixed it and will make a PR if Assigned !!

Hey! That's awesome! I have assigned you the issue!
